apiVersion: v1
kind: Service
metadata:
  name: jaseci-memcache
spec:
  selector:
    pod: jaseci-memcache
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaseci-memcache
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: jaseci-memcache
  template:
    metadata:
      labels:
        pod: jaseci-memcache
    spec:
      containers:
        - name: jaseci-redis-master
          image: redis
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "0.2"
          ports:
            - containerPort: 6379
