---
# Permit co-located instances for solitary minikube virtual machines.
antiAffinity: "soft"

secret:
  enabled: true
  password: ""

replicas: 1

# Shrink default JVM heap.
esJavaOpts: "-Xmx128m -Xms128m"

nodetype: single-node
clusterHealthCheckParams: "wait_for_status=yellow&timeout=1s" 

# This is just a dummy file to make sure that
# the keystore can be mounted at the same time
# as a custom elasticsearch.yml
esConfig:
  elasticsearch.yml: |
    xpack.security.enabled: false
    path.data: /usr/share/elasticsearch/data

# Allocate smaller chunks of memory per pod.
resources:
  requests:
    cpu: "100m"
    memory: "512M"
  limits:
    cpu: "1000m"
    memory: "512M"

# Request smaller persistent volumes.
volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "standard"
  resources:
    requests:
      storage: 100M
