apiVersion: v1
kind: Service
metadata:
  name: jst5
spec:
  selector:
    pod: jst5
  ports:
    - protocol: TCP
      port: 4674
      targetPort: 4674
      name: http
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jst5-up
  namespace: default
data:
  prod_up: |-
    mkdir /dl; cd /dl; git clone https://prod:$GITPASS@git.jaseci.org/marsninja/jaseci.git;
    cd jaseci; git checkout t5-summarization; cd /dl;
    mv jaseci/ai_serving /;
    cd /ai_serving/;
    python3 -m t5.t5_app;
---
apiVersion: v1
kind: Secret
metadata:
  name: jst5-git-pass
type: Opaque
data:
  password: UHIwZE4xbmo0
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5qYXNlY2kub3JnIjp7InVzZXJuYW1lIjoiamFzZWNpIiwicGFzc3dvcmQiOiJqNHMzYzEiLCJlbWFpbCI6Imphc29uQG1hcnMubmluamEiLCJhdXRoIjoiYW1GelpXTnBPbW8wY3pOak1RPT0ifX19
kind: Secret
metadata:
  name: jst5regcred
type: kubernetes.io/dockerconfigjson
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jst5
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: jst5
  template:
    metadata:
      labels:
        pod: jst5
      name: jst5
    spec:
      imagePullSecrets:
        - name: jst5regcred
      containers:
        - name: jst5
          image: registry.jaseci.org/jst5:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "4Gi"
            limits:
              memory: "4Gi"
          command: [bash, -c, "source script/prod_up"]
          ports:
            - containerPort: 4674
          env:
            - name: GITPASS
              valueFrom:
                secretKeyRef:
                  name: jst5-git-pass
                  key: password
          volumeMounts:
            - name: prod-script
              mountPath: /script

      volumes:
        - name: prod-script
          configMap:
            name: jst5-up
