apiVersion: v1
kind: Service
metadata:
  name: jsuse
spec:
  selector:
    pod: jsuse
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jsuse-up
  namespace: default
data:
  prod_up: |-
    apt update; apt -y upgrade; apt -y install git;
    git clone https://github.com/Jaseci-Labs/jaseci.git /jaseci/
    cd /jaseci
    git checkout action_new_interface
    cd /jaseci/jaseci_core/
    apt -y install --no-install-recommends python3.8 python3-pip vim;
    source install.sh
    cd /jaseci/jskit/use
    pip3 install -r requirements.txt
    uvicorn use:app --host 0.0.0.0 --port 80 --reload
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jsuse
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: jsuse
  template:
    metadata:
      labels:
        pod: jsuse
      name: jsuse
    spec:
      containers:
        - name: jsuse
          imagePullPolicy: IfNotPresent
          image: ubuntu:20.04
          resources:
            requests:
              memory: "3Gi"
            limits:
              memory: "3Gi"
          command: [bash, -c, "source script/prod_up"]
          ports:
            - containerPort: 80
          volumeMounts:
            - name: prod-script
              mountPath: /script

      volumes:
        - name: prod-script
          configMap:
            name: jsuse-up
