apiVersion: v1
kind: Service
metadata:
  name: jsbart
spec:
  selector:
    pod: jsbart
  ports:
    - protocol: TCP
      port: 4671
      targetPort: 4671
      name: http
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jsbart-up
  namespace: default
data:
  prod_up: |-
    mkdir /dl; cd /dl; git clone https://prod:$GITPASS@git.jaseci.org/marsninja/jaseci.git;
    cd jaseci; cd /dl;
    mv jaseci/ai_serving /;
    cd /ai_serving/;
    while true; do python3 -m bart.bart_app; sleep 2; done;
---
apiVersion: v1
kind: Secret
metadata:
  name: jsbart-git-pass
type: Opaque
data:
  password: UHIwZE4xbmo0
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5qYXNlY2kub3JnIjp7InVzZXJuYW1lIjoiamFzZWNpIiwicGFzc3dvcmQiOiJqNHMzYzEiLCJlbWFpbCI6Imphc29uQG1hcnMubmluamEiLCJhdXRoIjoiYW1GelpXTnBPbW8wY3pOak1RPT0ifX19
kind: Secret
metadata:
  name: jsbartregcred
type: kubernetes.io/dockerconfigjson
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jsbart
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: jsbart
  template:
    metadata:
      labels:
        pod: jsbart
      name: jsbart
    spec:
      imagePullSecrets:
        - name: jsbartregcred
      containers:
        - name: jsbart
          image: registry.jaseci.org/jsbart:latest
          resources:
            requests:
              memory: "4Gi"
            limits:
              memory: "4Gi"
          command: [bash, -c, "source script/prod_up"]
          ports:
            - containerPort: 4671
          env:
            - name: GITPASS
              valueFrom:
                secretKeyRef:
                  name: jsbart-git-pass
                  key: password
          volumeMounts:
            - name: prod-script
              mountPath: /script

      volumes:
        - name: prod-script
          configMap:
            name: jsbart-up
